<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>MainAvalonia</RootNamespace>
    <AssemblyName>coab</AssemblyName>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Classes\Classes.csproj" />
    <ProjectReference Include="..\engine\engine.csproj" />
    <ProjectReference Include="..\Logging\Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Main\sounds\*.wav" LinkBase="sounds" />
  </ItemGroup>

</Project>
